name:Cek Kode HTML(Windows)
on:
  push:
    -main
  pull_request:

  jobs:
    lint:
      runs-on:windows-latest

      steps:
        -name:Checkout Repository
         uses:actions/checkout@v4

        -name:InstallHTMLHint
         run:npminstall -g htmlhint

        -name:PeriksaHTML
         run:htmlhint"**/*.html"
